import {size} from './size';
import {color} from './color';
import {images} from '../assets/images/product';
export const data = [
    {
        id: 0,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[1], images[0], images[2], images[3]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 1,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[4], images[1], images[2], images[3]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 2,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[5], images[3], images[1], images[0]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 4,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[0], images[3], images[1], images[2]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 3,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[2], images[3], images[1], images[0]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 5,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        star: '4.5',
        images: [images[2], images[3], images[1], images[0]],
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 6,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[3], images[4], images[1], images[0]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 7,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[0], images[3], images[1], images[5]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 8,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[0], images[2], images[1], images[5]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
    {
        id: 9,
        like: false,
        name: "Women's Plain Regular Fit Shirt",
        price: '15.5',
        images: [images[1], images[0], images[2], images[3]],
        star: '4.5',
        size: size,
        color: color,
        description: 'Use filler text that has be edited for length an format to match the characteristics of real content as closely.',
        dimiessions: '29 x 25 x 25 CM ( 170 Gams )',
        manufacture: 'Fabricorn',
        countryOrigin: 'New York',
        weight: '170 G',
        fabric: '100% Cotton',
        style: 'Regular',
        neckStyle: 'Turtle Neck',
        pattern: 'Solid'
    },
]