export const RouteName = {
  Intro: '[Screen] Intro',
  Login: '[Screen] Login',
  Main: '[Screen] Main',
  ForgotPassword: '[Screen] Forgot Password',
  Register: '[Screen] Register',
  Home: '[Screen] Home',
  Profile: '[Screen] Profile',
  FashionMenu: '[Screen] Fashion Menu',
  Filter: '[Screen] Filter',
  ProductDetail: '[Screen] Product Detail',
  Cart: '[Screen] Cart',
  Checkout: '[Screen] Checkout',
  CheckoutAlter: '[Screen] Checkout Alter',
  DeliveryAddress: '[Screen] Delivery Address',
  Card: '[Screen] Card',
  TrackOrder: '[Screen] Check Order',
  EditProfile: '[Screen] Edit Profile',
  ChangePassword: '[Screen] Change Password',
  Order: '[Screen] Order',
  WriteReview: '[Screen] Write Review',
  Notification: '[Screen] Notification',
  WishList: '[Screen] Wish List',
  Search: '[Screen] Search',
};
